name: Deploy develop branch

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@v3
      with:
        args: deploy --stage dev --region ${{ secrets.AWS_REGION }}
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DATABASE_USERNAME_DEV: ${{ secrets.DATABASE_USERNAME_DEV }}
        DATABASE_PASSWORD_DEV: ${{ secrets.DATABASE_PASSWORD_DEV }}
        DATABASE_NAME_DEV: ${{ secrets.DATABASE_NAME_DEV }}
        DATABASE_HOST_DEV: ${{ secrets.DATABASE_HOST_DEV }}
        DATABASE_PORT_DEV: ${{ secrets.DATABASE_PORT_DEV }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME_DEV }}
        NODE_ENV: 'development'