name: Pull request quality checks

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  pull_request_checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up node 
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint

      - name: Run tests
        run: npm test
